name: "[internal] Produce analytic data"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      test_workflow_run_id:
        description: "Unique GitHub workflow run ID to use for data"
        type: number
      test_workflow_run_attempt:
        description: "Run attempt of the workflow run"
        default: 1
        type: number
  workflow_run:
    workflows: # List workflow that we want to collect data for
      - "Build and Test"
      - "On PR"
      - "On push"
    types:
      - completed

jobs:

  produce-cicd-data:

    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
      - name: Produce CICD Data
        # uses: tenstorrent/tt-forge-fe/.github/actions/produce-cicd-data@main # from antoher repo
        uses: ./.github/actions/produce-cicd-data
        with:
          test_workflow_run_id: ${{ inputs.test_workflow_run_id }}
          test_workflow_run_attempt: ${{ inputs.test_workflow_run_attempt }}
